In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('Dataset-SA.csv')

In [ ]:
df.head()

product_name product_price Rate  \
0  Candes 12 L Room/Personal Air Cooler??????(Whi...          3999    5   
1  Candes 12 L Room/Personal Air Cooler??????(Whi...          3999    5   
2  Candes 12 L Room/Personal Air Cooler??????(Whi...          3999    3   
3  Candes 12 L Room/Personal Air Cooler??????(Whi...          3999    1   
4  Candes 12 L Room/Personal Air Cooler??????(Whi...          3999    3   

            Review                                            Summary  \
0           super!  great cooler excellent air flow and for this p...   
1          awesome              best budget 2 fit cooler nice cooling   
2             fair  the quality is good but the power of air is de...   
3  useless product                  very bad product its a only a fan   
4             fair                                      ok ok product   

  Sentiment  
0  positive  
1  positive  
2  positive  
3  negative  
4   neutral

In [ ]:
filtered_df = df[df['product_name'].str.contains('air cooler', case=False, na=False)]

# Get all unique occurrences
unique_products = filtered_df['product_name'].unique()

# Display the unique product names
print(unique_products)

['Candes 12 L Room/Personal Air Cooler??????(White, Black, Elegant High Speed-Honey Comb Cooling Pad & Ice Chamber, Blower)'
 'Candes 60 L Room/Personal Air Cooler??????(White, Black, CRETA)'
 'MAHARAJA WHITELINE 65 L Desert Air Cooler??????(White, Grey, Rambo Grey / AC-303)'
 'Crompton 75 L Desert Air Cooler??????(White, Teal, ACGC-DAC751)']


In [ ]:
pip install pandas scikit-learn nltk textblob vaderSentiment


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 3.7 MB/s eta 0:00:00


In [ ]:
pip install flair

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 9.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 36.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.3/139.3 kB 5.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.1/203.1 kB 14.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.3/14.3 MB 58.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 4.4 MB/s eta 0:00:00
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=628c53c654b4562047d14dd0a7e848ecb5b387d74cdc7339c657abb2c2a74c1a
  Stored in directory: /root/.cache/pip/w

In [ ]:
!pip install fuzzywuzzy[speedup]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.3/153.3 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 38.4 MB/s eta 0:00:00


In [ ]:
import pandas as pd
from textblob import TextBlob
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from fuzzywuzzy import process

In [ ]:
# Initialize VADER
vader_analyzer = SentimentIntensityAnalyzer()


In [ ]:
def get_vader_sentiment(text):
    score = vader_analyzer.polarity_scores(str(text))['compound']
    if score >0.05:
        return 'Positive'
    elif score < -0.05:
        return 'Negative'
    else:
        return 'Neutral'


In [ ]:
def get_textblob_sentiment(text):
    score = TextBlob(str(text)).sentiment.polarity
    if score > 0.05:
        return 'Positive'
    elif score < -0.05:
        return 'Negative'
    else:
        return 'Neutral'

# Apply sentiment analysis
df['vader_sentiment'] = df['Review'].apply(get_vader_sentiment)
df['textblob_sentiment'] = df['Review'].apply(get_textblob_sentiment)

# Display all unique product names
unique_products = df['product_name'].unique()

In [ ]:
from nltk.sentiment import SentimentIntensityAnalyzer
import nltk
nltk.download('vader_lexicon')

sia = SentimentIntensityAnalyzer()

def predict_sentiment(text):
    score = sia.polarity_scores(str(text))['compound']
    if score > 0.05:
        return 'positive'
    elif score <-0.05:
        return 'negative'
    else:
        return 'neutral'


[nltk_data] Downloading package vader_lexicon to /root/nltk_data...


In [ ]:
!pip install --upgrade pip
!pip install flair


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 13.9 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2


In [ ]:
!pip install -U pip setuptools wheel
!pip install flair==0.13.1 --quiet


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 8.3 MB/s  0:00:00
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.2.0
    Uninstalling setuptools-75.2.0:
      Successfully uninstalled setuptools-75.2.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.


In [ ]:
import pandas as pd
from flair.models import TextClassifier
from flair.data import Sentence
import torch


In [ ]:

import pandas as pd
import torch
from flair.models import TextClassifier
from flair.data import Sentence
from tqdm import tqdm
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

classifier = TextClassifier.load('sentiment')

# Move to GPU if available
if torch.cuda.is_available():
    classifier.to('cuda')
    print("Using GPU for Flair inference.")
else:
    print("Using CPU for Flair inference.")

# Single prediction function with confidence thresholds
def predict_flair_sentiment_single(text, pos_conf=0.60, neg_conf=0.60):
    if pd.isna(text) or str(text).strip() == "":
        return "unknown"
    s = Sentence(str(text))
    classifier.predict(s)
    if not s.labels:
        return "unknown"
    label = s.labels[0]
    lab_value = label.value.lower()
    score = label.score
    if lab_value == 'positive' and score >= pos_conf:
        return 'positive'
    elif lab_value == 'negative' and score >= neg_conf:
        return 'negative'
    else:
        return 'neutral'

# Batch prediction
def predict_flair_batch(texts, batch_size=64, pos_conf=0.60, neg_conf=0.60):
    sentences = [Sentence(str(t)) if not pd.isna(t) else Sentence("") for t in texts]
    results = [None] * len(sentences)

    for i in tqdm(range(0, len(sentences), batch_size), desc="Flair batches"):
        batch = sentences[i:i+batch_size]
        classifier.predict(batch)
        for idx, s in enumerate(batch, start=i):
            if not s.labels:
                results[idx] = "unknown"
            else:
                label = s.labels[0]
                lab_value = label.value.lower()
                score = label.score
                if lab_value == 'positive' and score >= pos_conf:
                    results[idx] = 'positive'
                elif lab_value == 'negative' and score >= neg_conf:
                    results[idx] = 'negative'
                else:
                    results[idx] = 'neutral'
    return results


#  Run Flair on your reviews

pos_confidence_threshold = 0.60
neg_confidence_threshold = 0.60

df['flair_sentiment'] = predict_flair_batch(
    df['Review'].fillna("").tolist(),
    batch_size=64,
    pos_conf=pos_confidence_threshold,
    neg_conf=neg_confidence_threshold
)

# Quick peek
print(df[['Review','flair_sentiment']].head())

# Evaluate vs ground truth

true_sentiment = (
    df['Sentiment']
    .fillna("unknown")
    .astype(str)
    .str.lower()
    .str.strip()
)

pred_flair = (
    df['flair_sentiment']
    .fillna("unknown")
    .astype(str)
    .str.lower()
    .str.strip()
)

mask = (true_sentiment != "unknown") & (pred_flair != "unknown")
true_clean = true_sentiment[mask]
pred_clean = pred_flair[mask]

print("Flair Accuracy:", round(accuracy_score(true_clean, pred_clean) * 100, 2), "%")
print("\nFlair Classification Report:")
print(classification_report(true_clean, pred_clean))
print("\nFlair Confusion Matrix:")
print(confusion_matrix(true_clean, pred_clean))


Streaming output truncated to the last 5000 lines.
2025-11-22 06:21:54,577 Warning: An empty Sentence was created! Are there empty strings in your dataset?
2025-11-22 06:21:54,579 Warning: An empty Sentence was created! Are there empty strings in your dataset?
2025-11-22 06:21:54,579 Warning: An empty Sentence was created! Are there empty strings in your dataset?
2025-11-22 06:21:54,580 Warning: An empty Sentence was created! Are there empty strings in your dataset?
2025-11-22 06:21:54,581 Warning: An empty Sentence was created! Are there empty strings in your dataset?
2025-11-22 06:21:54,581 Warning: An empty Sentence was created! Are there empty strings in your dataset?
2025-11-22 06:21:54,583 Warning: An empty Sentence was created! Are there empty strings in your dataset?
2025-11-22 06:21:54,583 Warning: An empty Sentence was created! Are there empty strings in your dataset?
2025-11-22 06:21:54,587 Warning: An empty Sentence was created! Are there empty strings in your dataset?
2025

Flair batches: 100%|██████████| 3204/3204 [41:44<00:00,  1.28it/s]


            Review flair_sentiment
0           super!        positive
1          awesome        positive
2             fair        negative
3  useless product        negative
4             fair        negative
Flair Accuracy: 87.34 %

Flair Classification Report:
              precision    recall  f1-score   support

    negative       0.60      0.87      0.71     24401
     neutral       0.05      0.00      0.00      8811
    positive       0.94      0.93      0.93    147176

    accuracy                           0.87    180388
   macro avg       0.53      0.60      0.55    180388
weighted avg       0.85      0.87      0.86    180388


Flair Confusion Matrix:
[[ 21165      3   3233]
 [  3310      1   5500]
 [ 10783     15 136378]]


In [ ]:
print(df.columns)


Index(['product_name', 'product_price', 'Rate', 'Review', 'Summary',
       'Sentiment', 'vader_sentiment', 'textblob_sentiment',
       'flair_sentiment'],
      dtype='object')


In [ ]:
#  Save DataFrame to CSV
df.to_csv('reviews_with_flair.csv', index=False)
#Download CSV to your computer
from google.colab import files
files.download('reviews_with_flair.csv')


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Clean actual sentiment
true_sentiment = (
    df['Sentiment']
    .fillna("unknown")
    .astype(str)
    .str.lower()
    .str.strip()
)

# Clean predicted sentiment from VADER
pred_sentiment = (
    df['vader_sentiment']
    .fillna("unknown")
    .astype(str)
    .str.lower()
    .str.strip()
)

# Filter out unknowns
mask = (true_sentiment != "unknown") & (pred_sentiment != "unknown")
true_clean = true_sentiment[mask]
pred_clean = pred_sentiment[mask]

# Accuracy
accuracy = accuracy_score(true_clean, pred_clean)
print("VADER Accuracy:", round(accuracy * 100, 2), "%")

print("\nClassification Report:")
print(classification_report(true_clean, pred_clean))

print("\nConfusion Matrix:")
print(confusion_matrix(true_clean, pred_clean))


VADER Accuracy: 67.9 %

Classification Report:
              precision    recall  f1-score   support

    negative       0.86      0.46      0.60     28232
     neutral       0.07      0.38      0.12     10239
    positive       0.92      0.74      0.82    166581

    accuracy                           0.68    205052
   macro avg       0.62      0.52      0.51    205052
weighted avg       0.87      0.68      0.75    205052


Confusion Matrix:
[[ 12871   9999   5362]
 [  1079   3882   5278]
 [  1066  43032 122483]]


In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Clean actual sentiment
true_sentiment = (
    df['Sentiment']
    .fillna("unknown")
    .astype(str)
    .str.lower()
    .str.strip()
)

# Clean TextBlob predicted sentiment
pred_tb = (
    df['textblob_sentiment']
    .fillna("unknown")
    .astype(str)
    .str.lower()
    .str.strip()
)

# Remove unknown values
mask = (true_sentiment != "unknown") & (pred_tb != "unknown")
true_clean = true_sentiment[mask]
pred_clean = pred_tb[mask]

# 1. Accuracy
accuracy = accuracy_score(true_clean, pred_clean)
print("TextBlob Accuracy:", round(accuracy * 100, 2), "%")

# 2. Classification report
print("\nTextBlob Classification Report:")
print(classification_report(true_clean, pred_clean))

# 3. Confusion matrix
print("\nTextBlob Confusion Matrix:")
print(confusion_matrix(true_clean, pred_clean))


TextBlob Accuracy: 63.17 %

TextBlob Classification Report:
              precision    recall  f1-score   support

    negative       0.86      0.46      0.60     28232
     neutral       0.05      0.35      0.09     10239
    positive       0.91      0.68      0.78    166581

    accuracy                           0.63    205052
   macro avg       0.61      0.49      0.49    205052
weighted avg       0.86      0.63      0.72    205052


TextBlob Confusion Matrix:
[[ 12891   9552   5789]
 [  1049   3560   5630]
 [  1064  52445 113072]]
